Tambah status kehadiran pada widget aparatur desa
OpenSID/tema-esensi pull request #13
Opened 2022-03-17 04:36 UTC by yogiperdana

Penambahan fitur terkait issue https://github.com/OpenSID/tema-esensi/issues/12

2022-03-18 06:46 UTC, dikisiswanto requested changes

2022-03-18 06:46 UTC, dikisiswanto commented on widgets/aparatur_desa.php
> +            <span class="btn btn-primay status-kehadiran">Hadir</span>
Mas ini ada typo `btn-primay` harusnya `btn-primary`. 

Untuk tampilan overlay di tema esensi seperti ini, jadi sepertinya class `status-kehadiran` tidak diperlukan. Bisa diganti `w-auto mx-auto inline-block`

<img width="292" alt="image" src="https://user-images.githubusercontent.com/22239074/158950657-bf6bb656-fcf9-4946-9dcb-3e2065b192e0.png">

2022-03-18 07:04 UTC, andifahruddinakas commented
Mas @yogiperdana, cek komentar.

2022-03-23 00:53 UTC, yogiperdana commented on widgets/aparatur_desa.php
> +            <span class="btn btn-primay status-kehadiran">Hadir</span>
Baik mas

2022-03-23 00:55 UTC, yogiperdana commented
Sudah mas @andifahruddinakas

2022-03-23 05:28 UTC, merged